export enum ImageColor {
  ALL = 'all',
  RED = 'red',
  ORANGE = 'orange',
  YELLOW = 'yellow',
  GREEN = 'green',
  TURQUOISE = 'turquoise',
  BLUE = 'blue',
  VIOLET = 'violet',
  PINK = 'pink',
  BROWN = 'brown',
  BLACK = 'black',
  GRAY = 'gray',
  WHITE = 'white',
}