# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Package for Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --check-files
      - run: yarn build
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dist
          path: dist

      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ../pexels-figma-plugin.zip ./dist

      - name: Create Release
        uses: ncipollo/release-action@v1.6.1
        with:
          artifacts: pexels-figma-plugin.zip
          token: ${{ secrets.GITHUB_TOKEN }}
